version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tubecompany-backend
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Telegram__BotToken=${TELEGRAM_BOT_TOKEN}
      - App__BaseUrl=${APP_BASE_URL}
    volumes:
      - ./backend/Data:/app/Data
    networks:
      - tubecompany-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-tubecompany}
      PGDATA: /var/lib/postgresql/data
    networks:
      - tubecompany-network
    ports:
      - "5433:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-tubecompany}"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tubecompany-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - tubecompany-network
    restart: unless-stopped

networks:
  tubecompany-network:
    driver: bridge

volumes:
  postgres_data: