version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tubecompany-backend
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Telegram__BotToken=${TELEGRAM_BOT_TOKEN:-}
      - App__BaseUrl=${APP_BASE_URL:-http://localhost:5000}
    volumes:
      - ./backend/Data:/app/Data
    networks:
      - tubecompany-network
    restart: unless-stopped

networks:
  tubecompany-network:
    driver: bridge